language: c
arch: arm64

git:
     depth: 1

services:
     - docker

env:
  - NEXT=next-20210107

stages:
  - builddb
  - build1

jobs:
  include:
    - stage: build1
      name: smatch
      before_script:
       - docker pull sudipm/smatch:arm
      script:
        - oldpwd=`pwd`
        - cd $HOME
        - travis_retry git clone --single-branch -b smatch https://oauth2:$GL@gitlab.com/sudipm/smatchdb.git
        - cd $oldpwd
        - wget https://gitlab.com/sudipm/smatchdb/-/raw/master/backup.tar.bz2
        - docker run -v "$PWD":/src --workdir /src sudipm/smatch:arm /bin/bash -c "./build.sh smatch olddefconfig"
        - cp smatch_warns.txt.tar.bz2 $HOME/smatchdb/backup.tar.bz2
        - git clean -fdx || true
        - cd $HOME/smatchdb
        - git config user.email "sudipm.mukherjee@gmail.com"
        - git config user.name "Travis CI"
        - git add -f backup.tar.bz2
        - git commit -s -m "clang update"
        - travis_retry git push -v origin smatch

    - stage: builddb
      name: smatchdb
      cache:
        directories:
        - $HOME/backup
      before_script:
       - docker pull sudipm/smatch:arm
       - mkdir -p $HOME/backup
      script:
        - oldpwd=`pwd`
        - cd $HOME
        - travis_retry git clone --single-branch -b master https://oauth2:$GL@gitlab.com/sudipm/smatchdb.git
        - cd $oldpwd
        - if [ -f $HOME/backup/version ]; then cat $HOME/backup/version; fi
        - mv $HOME/smatchdb/backup.tar.bz2 .  || true
        - docker run -v "$PWD":/src --workdir /src sudipm/smatch:arm /bin/bash -c "./build.sh smatchdb2 defconfig"
        - mv backup.tar.bz2 $HOME/smatchdb/.
        - git clean -fdx || true
        - cd $HOME/smatchdb
        - git add -f backup.tar.bz2
        - git commit -s -m "smatch db update"
        - travis_retry git push -v origin
